/**
 * The demo's customers: invented people, each at an invented door on a real street of
 * a city the shop ships to. `demo-plan.ts` takes them in this order.
 */

export interface City {
  readonly city: string;
  readonly province: string | null;
  readonly postalCode: string;
  readonly countryCode: string;
  readonly street: string;
}

/** Real cities and streets, invented door numbers: the shop ships to every one. */
export const CITIES = {
  portland: {
    city: 'Portland',
    province: 'OR',
    postalCode: '97205',
    countryCode: 'US',
    street: 'SW Taylor Street',
  },
  chicago: {
    city: 'Chicago',
    province: 'IL',
    postalCode: '60614',
    countryCode: 'US',
    street: 'N Halsted Street',
  },
  brooklyn: {
    city: 'Brooklyn',
    province: 'NY',
    postalCode: '11215',
    countryCode: 'US',
    street: '7th Avenue',
  },
  austin: {
    city: 'Austin',
    province: 'TX',
    postalCode: '78701',
    countryCode: 'US',
    street: 'Congress Avenue',
  },
  saoPaulo: {
    city: 'São Paulo',
    province: 'SP',
    postalCode: '01310-100',
    countryCode: 'BR',
    street: 'Avenida Paulista',
  },
  rio: {
    city: 'Rio de Janeiro',
    province: 'RJ',
    postalCode: '22410-001',
    countryCode: 'BR',
    street: 'Rua Visconde de Pirajá',
  },
  beloHorizonte: {
    city: 'Belo Horizonte',
    province: 'MG',
    postalCode: '30130-010',
    countryCode: 'BR',
    street: 'Avenida Afonso Pena',
  },
  curitiba: {
    city: 'Curitiba',
    province: 'PR',
    postalCode: '80020-310',
    countryCode: 'BR',
    street: 'Rua XV de Novembro',
  },
  london: {
    city: 'London',
    province: null,
    postalCode: 'EC1V 4PW',
    countryCode: 'GB',
    street: 'Old Street',
  },
  manchester: {
    city: 'Manchester',
    province: null,
    postalCode: 'M4 1HN',
    countryCode: 'GB',
    street: 'Oldham Street',
  },
  edinburgh: {
    city: 'Edinburgh',
    province: null,
    postalCode: 'EH1 1QS',
    countryCode: 'GB',
    street: 'Cockburn Street',
  },
  tokyo: {
    city: 'Tokyo',
    province: 'Tokyo',
    postalCode: '150-0001',
    countryCode: 'JP',
    street: 'Jingūmae, Shibuya-ku',
  },
  kyoto: {
    city: 'Kyoto',
    province: 'Kyoto',
    postalCode: '604-8005',
    countryCode: 'JP',
    street: 'Kawaramachi-dōri, Nakagyō-ku',
  },
  berlin: {
    city: 'Berlin',
    province: null,
    postalCode: '10119',
    countryCode: 'DE',
    street: 'Torstraße',
  },
  hamburg: {
    city: 'Hamburg',
    province: null,
    postalCode: '20457',
    countryCode: 'DE',
    street: 'Am Sandtorkai',
  },
  paris: {
    city: 'Paris',
    province: null,
    postalCode: '75003',
    countryCode: 'FR',
    street: 'Rue de Bretagne',
  },
  lyon: {
    city: 'Lyon',
    province: null,
    postalCode: '69001',
    countryCode: 'FR',
    street: 'Rue de la République',
  },
  montreal: {
    city: 'Montréal',
    province: 'QC',
    postalCode: 'H2X 1Y5',
    countryCode: 'CA',
    street: 'Boulevard Saint-Laurent',
  },
  toronto: {
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M5V 2H1',
    countryCode: 'CA',
    street: 'Queen Street West',
  },
  amsterdam: {
    city: 'Amsterdam',
    province: null,
    postalCode: '1015 CJ',
    countryCode: 'NL',
    street: 'Prinsengracht',
  },
  milano: {
    city: 'Milano',
    province: 'MI',
    postalCode: '20121',
    countryCode: 'IT',
    street: 'Via Brera',
  },
  roma: {
    city: 'Roma',
    province: 'RM',
    postalCode: '00186',
    countryCode: 'IT',
    street: 'Via dei Coronari',
  },
  madrid: {
    city: 'Madrid',
    province: null,
    postalCode: '28004',
    countryCode: 'ES',
    street: 'Calle de Fuencarral',
  },
  lisboa: {
    city: 'Lisboa',
    province: null,
    postalCode: '1200-195',
    countryCode: 'PT',
    street: 'Rua Garrett',
  },
  melbourne: {
    city: 'Melbourne',
    province: 'VIC',
    postalCode: '3000',
    countryCode: 'AU',
    street: 'Flinders Lane',
  },
  sydney: {
    city: 'Sydney',
    province: 'NSW',
    postalCode: '2010',
    countryCode: 'AU',
    street: 'Crown Street',
  },
  stockholm: {
    city: 'Stockholm',
    province: null,
    postalCode: '118 20',
    countryCode: 'SE',
    street: 'Götgatan',
  },
  mexico: {
    city: 'Ciudad de México',
    province: 'CDMX',
    postalCode: '06700',
    countryCode: 'MX',
    street: 'Calle Colima',
  },
  seoul: {
    city: 'Seoul',
    province: null,
    postalCode: '04524',
    countryCode: 'KR',
    street: 'Sejong-daero',
  },
  dublin: {
    city: 'Dublin',
    province: null,
    postalCode: 'D02 X285',
    countryCode: 'IE',
    street: 'Grafton Street',
  },
} as const satisfies Record<string, City>;

/** Invented people, in the order the plan takes them: the first come back most. */
export const PEOPLE: readonly { firstName: string; lastName: string; city: keyof typeof CITIES }[] =
  [
    { firstName: 'Maya', lastName: 'Thompson', city: 'portland' },
    { firstName: 'Ana Beatriz', lastName: 'Souza', city: 'saoPaulo' },
    { firstName: 'Eleanor', lastName: 'Hughes', city: 'london' },
    { firstName: 'Haruka', lastName: 'Sato', city: 'tokyo' },
    { firstName: 'Daniel', lastName: 'Rivera', city: 'chicago' },
    { firstName: 'Lucas', lastName: 'Oliveira', city: 'rio' },
    { firstName: 'Lena', lastName: 'Fischer', city: 'berlin' },
    { firstName: 'Grace', lastName: 'Kim', city: 'brooklyn' },
    { firstName: 'Camille', lastName: 'Laurent', city: 'paris' },
    { firstName: 'Mariana', lastName: 'Costa', city: 'beloHorizonte' },
    { firstName: 'Oliver', lastName: 'Grant', city: 'manchester' },
    { firstName: 'Chloé', lastName: 'Tremblay', city: 'montreal' },
    { firstName: 'Ethan', lastName: 'Brooks', city: 'austin' },
    { firstName: 'Kenji', lastName: 'Watanabe', city: 'kyoto' },
    { firstName: 'Rafael', lastName: 'Lima', city: 'curitiba' },
    { firstName: 'Sanne', lastName: 'de Vries', city: 'amsterdam' },
    { firstName: 'Giulia', lastName: 'Romano', city: 'milano' },
    { firstName: 'Olivia', lastName: 'Bennett', city: 'portland' },
    { firstName: 'Juliana', lastName: 'Pereira', city: 'saoPaulo' },
    { firstName: 'Isla', lastName: 'Murray', city: 'edinburgh' },
    { firstName: 'Jonas', lastName: 'Becker', city: 'hamburg' },
    { firstName: 'Lucía', lastName: 'García', city: 'madrid' },
    { firstName: 'Charlotte', lastName: 'Nguyen', city: 'melbourne' },
    { firstName: 'Marcus', lastName: 'Hill', city: 'chicago' },
    { firstName: 'Thiago', lastName: 'Almeida', city: 'rio' },
    { firstName: 'Hugo', lastName: 'Moreau', city: 'lyon' },
    { firstName: 'Inês', lastName: 'Ferreira', city: 'lisboa' },
    { firstName: 'Noah', lastName: 'Campbell', city: 'toronto' },
    { firstName: 'Yui', lastName: 'Tanaka', city: 'tokyo' },
    { firstName: 'Samuel', lastName: 'Price', city: 'london' },
    { firstName: 'Astrid', lastName: 'Lindqvist', city: 'stockholm' },
    { firstName: 'Valeria', lastName: 'Hernández', city: 'mexico' },
    { firstName: 'Camila', lastName: 'Rocha', city: 'saoPaulo' },
    { firstName: 'Marco', lastName: 'Ricci', city: 'roma' },
    { firstName: 'Sofia', lastName: 'Alvarez', city: 'austin' },
    { firstName: 'Ji-woo', lastName: 'Park', city: 'seoul' },
    { firstName: 'Mia', lastName: 'Wagner', city: 'berlin' },
    { firstName: 'Jack', lastName: 'Wilson', city: 'sydney' },
    { firstName: 'Aoife', lastName: 'Byrne', city: 'dublin' },
    { firstName: 'Henry', lastName: 'Walsh', city: 'brooklyn' },
  ];
