import type { Config, DesignTokens, Dictionary, TransformedToken } from 'style-dictionary/types';
import { getReferences } from 'style-dictionary/utils';
import { namespaced } from './collections.ts';
import { contrastPairs, contrastRatio } from './contrast.ts';
import { cssValue } from './values.ts';

const HEADER = '/* Generated by @deckle/tokens from tokens/*.tokens.json. Do not edit. */';

const pathOf = (token: TransformedToken) => token.path.slice(1).join('.');
const inCollection = (dictionary: Dictionary, collection: string) =>
  dictionary.allTokens.filter((token) => token.path[0] === collection);

/** The primitive a semantic or role token aliases. Every one of them aliases exactly one. */
function primitiveOf(token: TransformedToken, dictionary: Dictionary): TransformedToken {
  const original = token.original.$value as unknown;
  const references =
    typeof original === 'string'
      ? getReferences(original, dictionary.tokens, { usesDtcg: true })
      : [];
  const [target] = references;
  if (references.length !== 1 || target?.path[0] !== 'primitive') {
    throw new Error(`${token.path.join('.')} must alias exactly one primitive`);
  }
  return target;
}

/** Light tokens with their dark twin; a token in one mode only is a mistake. */
function modePairs(dictionary: Dictionary): [TransformedToken, TransformedToken][] {
  const dark = new Map(inCollection(dictionary, 'dark').map((token) => [pathOf(token), token]));
  const pairs: [TransformedToken, TransformedToken][] = [];
  const missing: string[] = [];
  for (const token of inCollection(dictionary, 'light')) {
    const twin = dark.get(pathOf(token));
    if (twin === undefined) {
      missing.push(`${pathOf(token)} (dark)`);
    } else {
      pairs.push([token, twin]);
      dark.delete(pathOf(token));
    }
  }
  missing.push(...[...dark.keys()].map((path) => `${path} (light)`));
  if (missing.length > 0) {
    throw new Error(`Each semantic token needs both modes; missing: ${missing.join(', ')}`);
  }
  return pairs;
}

const camel = (segment: string) =>
  segment.replace(/-([a-z0-9])/g, (_match, c: string) => c.toUpperCase());

interface Tree {
  [key: string]: Tree | string;
}

/** `{ surface: { page: 'var(--surface-page)' } }`: what components read, primitives left out. */
function semanticTree(dictionary: Dictionary): Tree {
  const tree: Tree = {};
  const tokens = [
    ...modePairs(dictionary).map(([light]) => light),
    ...inCollection(dictionary, 'role'),
  ];
  for (const token of tokens) {
    const keys = token.path.slice(1).map(camel);
    const parents = keys.slice(0, -1);
    const leaf = keys.at(-1) ?? '';
    let node = tree;
    for (const key of parents) {
      const next = (node[key] ??= {});
      if (typeof next === 'string') {
        throw new Error(`${token.path.join('.')} collides with a token named ${key}`);
      }
      node = next;
    }
    if (leaf in node) {
      throw new Error(`Two tokens become ${keys.join('.')}`);
    }
    node[leaf] = `var(--${token.name})`;
  }
  return tree;
}

/** Media queries cannot read custom properties, so breakpoints are written out in rem. */
function mediaQueries(dictionary: Dictionary): Record<string, string> {
  return Object.fromEntries(
    inCollection(dictionary, 'primitive')
      .filter((token) => token.path[1] === 'breakpoint')
      .map((token) => {
        const { value } = token.original.$value as { value: number };
        return [token.path[2] ?? '', `(min-width: ${String(value / 16)}rem)`];
      }),
  );
}

function declaration(tree: Tree, depth = 1): string {
  const indent = '  '.repeat(depth);
  const lines = Object.entries(tree).map(([key, value]) =>
    typeof value === 'string'
      ? `${indent}readonly ${key}: '${value}';`
      : `${indent}readonly ${key}: ${declaration(value, depth + 1)};`,
  );
  return `{\n${lines.join('\n')}\n${'  '.repeat(depth - 1)}}`;
}

function foundations(dictionary: Dictionary) {
  const hexOf = (token: TransformedToken) => primitiveOf(token, dictionary).$value as string;
  const pairs = modePairs(dictionary);
  const colourByPath = new Map(pairs.map(([light, dark]) => [pathOf(light), { light, dark }]));
  const role = (group: string) =>
    inCollection(dictionary, 'role')
      .filter((token) => token.path[1] === group)
      .map((token) => ({
        token: pathOf(token),
        cssVar: `--${token.name}`,
        value: primitiveOf(token, dictionary).$value as string,
        primitive: pathOf(primitiveOf(token, dictionary)),
      }));
  const type = Object.groupBy(role('type'), (entry) => entry.token.split('.')[1] ?? '');

  return {
    colours: pairs.map(([light, dark]) => ({
      token: pathOf(light),
      cssVar: `--${light.name}`,
      light: { primitive: pathOf(primitiveOf(light, dictionary)), hex: hexOf(light) },
      dark: { primitive: pathOf(primitiveOf(dark, dictionary)), hex: hexOf(dark) },
    })),
    palettes: Object.entries(
      Object.groupBy(
        inCollection(dictionary, 'primitive').filter((token) => token.path[1] === 'color'),
        (token) => token.path[2] ?? '',
      ),
    ).map(([palette, tokens = []]) => ({
      palette,
      steps: tokens.map((token) => ({ step: token.path[3], hex: token.$value as string })),
    })),
    type: Object.entries(type).map(([name, entries = []]) => ({
      role: name,
      ...Object.fromEntries(
        entries.map((entry): [string, string] => [entry.token.split('.')[2] ?? '', entry.value]),
      ),
    })),
    space: role('space'),
    radius: role('radius'),
    strokeWidth: role('stroke-width'),
    motion: role('motion'),
    layout: role('layout'),
    breakpoints: Object.entries(mediaQueries(dictionary)).map(([name, query]) => ({ name, query })),
    contrast: contrastPairs.map((pair) => {
      const ratio = (mode: 'light' | 'dark') => {
        const foreground = colourByPath.get(pair.foreground)?.[mode];
        const background = colourByPath.get(pair.background)?.[mode];
        if (foreground === undefined || background === undefined) {
          throw new Error(
            `Contrast pair names a missing token: ${pair.foreground} on ${pair.background}`,
          );
        }
        return Math.round(contrastRatio(hexOf(foreground), hexOf(background)) * 100) / 100;
      };
      return { ...pair, light: ratio('light'), dark: ratio('dark') };
    }),
  };
}

export interface ConfigOptions {
  /** Globs for the token files; tests point it at fixtures. */
  source?: string[];
  buildPath?: string;
}

export function createConfig({
  source = ['tokens/*.tokens.json'],
  buildPath = 'dist/',
}: ConfigOptions = {}): Config {
  return {
    source,
    log: { warnings: 'error', verbosity: 'silent' },
    parsers: ['deckle/collections'],
    hooks: {
      parsers: {
        'deckle/collections': {
          pattern: /\.tokens\.json$/,
          parser: ({ filePath = '', contents }) => namespaced(filePath, contents) as DesignTokens,
        },
      },
      transforms: {
        'deckle/name': {
          type: 'name',
          // A dark token is only ever written as the second half of its light twin's
          // light-dark(), so its own name stays internal; it must still be unique.
          transform: (token) => {
            const [collection, ...path] = token.path;
            const prefixes: Record<string, string> = { primitive: 'p-', dark: 'dark-' };
            const prefix = prefixes[collection ?? ''] ?? '';
            return `${prefix}${path.join('-')}`;
          },
        },
        'deckle/value': {
          type: 'value',
          filter: (token) => token.path[0] === 'primitive',
          transform: (token) => cssValue(token as unknown as Parameters<typeof cssValue>[0]),
        },
      },
      formats: {
        'deckle/css': ({ dictionary }) => {
          const reference = (token: TransformedToken) =>
            `var(--${primitiveOf(token, dictionary).name})`;
          const lines = [
            '  /* Primitives: for the semantic layer below, never read by a component. */',
            ...inCollection(dictionary, 'primitive')
              .filter((token) => token.path[1] !== 'breakpoint')
              .map((token) => `  --${token.name}: ${String(token.$value)};`),
            '',
            '  /* Semantic colours, light and dark. */',
            ...modePairs(dictionary).map(
              ([light, dark]) =>
                `  --${light.name}: light-dark(${reference(light)}, ${reference(dark)});`,
            ),
            '',
            '  /* Roles: type, space, radius, motion and layout. */',
            ...inCollection(dictionary, 'role').map(
              (token) => `  --${token.name}: ${reference(token)};`,
            ),
          ];
          return [
            HEADER,
            '',
            ':root {',
            '  color-scheme: light dark;',
            ...lines,
            '}',
            '',
            "/* A choice the reader made overrides the system's. */",
            ":root[data-theme='light'] {",
            '  color-scheme: light;',
            '}',
            '',
            ":root[data-theme='dark'] {",
            '  color-scheme: dark;',
            '}',
            '',
          ].join('\n');
        },
        'deckle/js': ({ dictionary }) =>
          [
            HEADER,
            `export const tokens = ${JSON.stringify(semanticTree(dictionary), null, 2)};`,
            `export const media = ${JSON.stringify(mediaQueries(dictionary), null, 2)};`,
            '',
          ].join('\n'),
        'deckle/dts': ({ dictionary }) =>
          [
            HEADER,
            '/** Semantic and role tokens as CSS custom properties. Primitives are not exported. */',
            `export declare const tokens: ${declaration(semanticTree(dictionary))};`,
            `export declare const media: ${declaration(
              Object.fromEntries(Object.entries(mediaQueries(dictionary))),
            )};`,
            'export type Tokens = typeof tokens;',
            '',
          ].join('\n'),
        'deckle/foundations': ({ dictionary }) =>
          `${JSON.stringify(foundations(dictionary), null, 2)}\n`,
      },
    },
    platforms: {
      web: {
        transforms: ['deckle/name', 'deckle/value'],
        buildPath,
        files: [
          { destination: 'tokens.css', format: 'deckle/css' },
          { destination: 'index.js', format: 'deckle/js' },
          { destination: 'index.d.ts', format: 'deckle/dts' },
          { destination: 'foundations.json', format: 'deckle/foundations' },
        ],
      },
    },
  };
}
