// Writes src/styles/fonts.css: the faces Deckle serves, and for each a fallback whose
// metrics match it, so text keeps its place while the web font loads.
// `pnpm --filter @deckle/ui fonts` after replacing a font file.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import { fromFile } from '@capsizecss/unpack/fs';
import { format, resolveConfig } from 'prettier';

const fontsDir = new URL('../src/fonts/', import.meta.url);
const outFile = new URL('../src/styles/fonts.css', import.meta.url);

// The Latin subset the files were cut to: enough for English and Portuguese.
const unicodeRange =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

const metrics = await fromFile(fileURLToPath(new URL('host-grotesk-normal.woff2', fontsDir)));
const { fontFaces } = createFontStack([{ ...metrics, familyName: 'Host Grotesk' }, arial], {
  fontFaceFormat: 'styleString',
});

const face = (style: 'normal' | 'italic') => `@font-face {
  font-family: 'Host Grotesk';
  font-style: ${style};
  font-weight: 300 800;
  font-display: swap;
  src: url('../fonts/host-grotesk-${style}.woff2') format('woff2');
  unicode-range: ${unicodeRange};
}`;

const css = `/* Generated by scripts/fonts.ts. Host Grotesk is under the SIL Open Font License (src/fonts/OFL.txt). */

${face('normal')}

${face('italic')}

/* Arial resized to Host Grotesk's metrics: the fallback takes the same space, so nothing shifts on swap. */
${fontFaces}
`;

// Written as the formatter would write it, so a regenerated file is the committed one.
const options = await resolveConfig(fileURLToPath(outFile));
await writeFile(outFile, await format(css, { ...options, parser: 'css' }));
process.stdout.write('@deckle/ui: wrote src/styles/fonts.css\n');
