import { base, restrictImports } from '@deckle/eslint-config';

const framework = [
  'payload',
  'payload/**',
  '@payloadcms/**',
  'next',
  'next/**',
  'react',
  'react-dom',
];

/** Modules that state a contract or a rule and nothing else: no framework, so they test alone. */
const contracts = [
  'src/env.ts',
  'src/access/policy.ts',
  'src/access/api-key-guard.ts',
  'src/preview/**/*.ts',
  'src/rich-text/prose.ts',
  'src/webhooks/event.ts',
  'src/webhooks/publication.ts',
  'src/webhooks/signature.ts',
  'src/webhooks/deliver.ts',
];

export default [
  ...base,
  {
    // Generated by Payload (types, import map, migrations) or by Next.
    ignores: [
      '.next/',
      'dist/',
      'media/',
      'next-env.d.ts',
      'src/payload-types.ts',
      'src/migrations/',
      'src/app/(payload)/admin/importMap.js',
    ],
  },
  {
    files: contracts,
    ignores: ['**/*.spec.ts'],
    rules: {
      'no-restricted-imports': restrictImports({
        group: framework,
        message: 'Contract modules stay framework-free; wire them into Payload elsewhere.',
      }),
    },
  },
  {
    files: ['src/**/*.ts'],
    ignores: [...contracts, 'src/app/**', 'src/proxy.ts', '**/*.spec.ts'],
    rules: {
      'no-restricted-imports': restrictImports({
        group: ['next', 'next/**'],
        message: 'Next.js only hosts Payload here: it belongs in src/app and src/proxy.ts.',
      }),
    },
  },
];
