import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['src/**/*.spec.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: [
        // Entry points, their process wiring and the command-line tools: they only put
        // the modules below together, and the integration suite and the image run them.
        'src/index.ts',
        'src/index-worker.ts',
        'src/seed.ts',
        'src/process.ts',
        'src/tools/**',
        // Generated by TypeORM.
        'src/migrations/1*.ts',
        // Code that only means something against Postgres, which `test:integration`
        // runs for real (AGENTS.md: no mocks of the database).
        'src/database/migrate.ts',
        'src/plugins/catalogue-hooks/change-resolver.ts',
        'src/seed/seed-*.ts',
        'src/seed/shop-setup.ts',
        'src/seed/superadmin.ts',
      ],
      thresholds: { lines: 98, branches: 94, functions: 96, statements: 98 },
    },
  },
});
