// Turns each direction's DTCG token files into CSS custom properties, so the prototype
// reads the same tokens the design system will. Style Dictionary takes over once one is chosen.
//
// Primitives become `--p-*` and are for the semantic layer only; the page reads the
// unprefixed semantic names, each colour a `light-dark()` pair.
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';

const root = new URL('./tokens/', import.meta.url);
const out = new URL('./build/tokens.css', import.meta.url);

const isToken = (node) => node && typeof node === 'object' && '$value' in node;

function flatten(tree, path = [], acc = new Map()) {
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$')) continue;
    if (isToken(node)) acc.set([...path, key].join('.'), node);
    else flatten(node, [...path, key], acc);
  }
  return acc;
}

const varName = (path, prefix = '') => `--${prefix}${path.replaceAll('.', '-')}`;
const alias = (value) => (typeof value === 'string' ? /^\{(.+)\}$/.exec(value)?.[1] : undefined);

function cssValue(token, path) {
  const { $type: type, $value: value } = token;
  switch (type) {
    case 'color':
      return value.hex.toLowerCase();
    case 'dimension': {
      // Type and space scale in rem so they follow the reader's font size; rules and radii stay in px.
      const inRem = path.startsWith('font.size') || path.startsWith('space');
      return inRem ? `${value.value / 16}rem` : `${value.value}${value.unit}`;
    }
    case 'fontFamily':
      return value.map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ');
    case 'duration':
      return `${value.value}${value.unit}`;
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'number':
      return token.$description === 'em' ? `${value}em` : String(value);
    default:
      return String(value);
  }
}

async function direction(name) {
  const read = async (file) => JSON.parse(await readFile(new URL(`${name}/${file}`, root), 'utf8'));
  const [primitives, light, dark, roles] = await Promise.all([
    read('primitives.tokens.json'),
    read('semantic.light.tokens.json'),
    read('semantic.dark.tokens.json'),
    read('roles.tokens.json'),
  ]);

  const lines = [];
  for (const [path, token] of flatten(primitives)) {
    if (path.startsWith('breakpoint')) continue; // media queries cannot read custom properties
    lines.push(`  ${varName(path, 'p-')}: ${cssValue(token, path)};`);
  }

  const lightTokens = flatten(light);
  const darkTokens = flatten(dark);
  for (const [path, token] of lightTokens) {
    const pair = [token, darkTokens.get(path)].map((t) => `var(${varName(alias(t.$value), 'p-')})`);
    lines.push(`  ${varName(path)}: light-dark(${pair.join(', ')});`);
  }

  for (const [path, token] of flatten(roles)) {
    lines.push(`  ${varName(path)}: var(${varName(alias(token.$value), 'p-')});`);
  }

  return `:root[data-direction='${name}'] {\n${lines.join('\n')}\n}\n`;
}

const names = (await readdir(root, { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name);
const blocks = await Promise.all(names.map(direction));

await mkdir(new URL('./build/', import.meta.url), { recursive: true });
await writeFile(
  out,
  `/* Generated by build-tokens.mjs from tokens/*. Do not edit. */\n\n${blocks.join('\n')}`,
);
console.log(`wrote ${names.length} directions to build/tokens.css`);
